baseURL: "/"
languageCode: "pt-br"
languageLang: "pt"
title: "Jean Goes"

disableKinds:
- taxonomy
- term

params:
  dominio: https://jeangoes.netlify.app
  logoSite: /assets/img/jeangoes-logo.svg
  favSite: /assets/img/fav_jean.png
  thumbRect: /assets/img/jean_thumb.jpg
  thumbQuad: /assets/img/jean_thumb_quad.jpg
  description: Portfólio de Jean Goes.
  fotoPerfil: /assets/img/perfil_jean.jpg
  contactDescription: "Mussum Ipsum, cacilds vidis litro abertis. Mé faiz elementum girarzis, nisi eros vermeio eros epos epos."
  curriculum: /curriculum.pdf
  perfilVimeo:
    linkVimeoContact: https://vimeo.com/user72822778
    viewVimeo: true
  perfilYoutube:
    linkYoutubeContact: Coloque o link do YouTube aqui
    viewYoutube: false
  perfilInsta:
    linkInstaContact: https://www.instagram.com/jeangoes_/
    viewInsta: true
  perfilWhats:
    linkWhatsContact: Coloque o link do WhatsApp aqui
    viewWhats: true
  perfilLinkedin:
    linkLinkedinContact: https://www.linkedin.com/in/jean-goes-5b9abb11a/
    viewLinkedin: true
  perfilFace:
    linkFaceContact: Coloque o link do Facebook aqui
    viewFace: false